GodotModding/godot-mod-tool

godot-mod-export-tool-plugin/godot-3/addons/godot-mod-export/dock.gd
godot-mod-export-tool-plugin/godot-3/addons/godot-mod-export/dock.tscn
godot-mod-export-tool-plugin/godot-3/addons/godot-mod-export/plugin.gd

new manifest editor tab (doesn't do much yet)
made a new scene for these string inputs and changed the two from the export tab to those as well. you have to use `.get_value` now instead of getting the text from the input directly.
it also allows for some visual validation through ModManifest with `show_error_if_not(condition: bool)`

Edit manifest tab

---

godot-mod-export-tool-plugin/godot-3/addons/godot-mod-export/input_string.gd
godot-mod-export-tool-plugin/godot-3/addons/godot-mod-export/input_string_multiline.tscn

There is a bug in Godot where it incorrectly scrolls two nested scroll containers (scrollcontainer and textedit in this case) at the same time. There is no workaround, but we can just use the the textedit resize to "remove" the inner scroll in this case.

remove attempted fix of godot bug

---

addons/mod_tool/dock.gd
addons/mod_tool/dock.tscn
addons/mod_tool/store.gd

Moved editor base theme to store.gd so it's easier to access.
I left the *json_editor.gd* as is. Because it uses a set function on the `base_theme` var.

refactor: :recycle: moved editor base theme to store.gd

---

addons/mod_tool/build_zip.gd
addons/mod_tool/dock.gd
addons/mod_tool/plugin.gd
addons/mod_tool/store.gd
addons/mod_tool/utils.gd

Adding the ModToolStore as a singleton on `_enter_tree()` in *plugin.gd* allows easy access from any where in the plugin. Refactored every store reference to use the new singleton. The singleton get's removed in `_exit_tree()` in *plugin.gd*.

refactor: :recycle: Add / Remove ModToolStore as a singleton/autoload

---

addons/mod_tool/global/utils.gd

Use the `Directory` `copy()` method, instead of `File`.
```gdscript
static func file_copy(src: String, dst: String) -> void:
var file := File.new()
var dir := Directory.new()
var dst_dir := dst.get_base_dir()
file.open(src, File.READ)
var file_length := file.get_len()
var file_content := file.get_buffer(file_length)
file.close()
if not dir.dir_exists(dst_dir):
dir.make_dir_recursive(dst_dir)
file.open(dst, File.WRITE)
file.store_buffer(file_content)
file.close()
```
```gdscript
static func file_copy(src: String, dst: String) -> void:
var dir := Directory.new()
var dst_dir := dst.get_base_dir()
if not dir.dir_exists(dst_dir):
dir.make_dir_recursive(dst_dir)
dir.copy(src, dst)
```
*closes #43*

refactor: ♻️ Use the `Directory` `copy()` method

---

addons/mod_tool/global/store.gd

Fixed the unexpected argument type

fix: :ambulance: unexpected argument type

---

addons/mod_tool/interface/file_system/file_system_context_actions.gd
addons/mod_tool/plugin.gd

Reference will be freed automatically if there are no references to it anywhere

refactor: change input actions to reference to avoid freeing

---

addons/mod_tool/interface/config_editor/ModConfigEditor.tscn
addons/mod_tool/interface/panel/tools_panel.tscn

- Moved the Config Editor into a separate scene
- Temporarily removed the Config Editor tab from the UI until #56 is implemented.
works towards #6

refactor: :recycle: hide the config editor for now

---

addons/mod_tool/interface/panel/tools_panel.tscn

- Temporarily hide the Export Types until #39 is implemented.
closes #61

refactor: :recycle: hide the export type option for now

---

addons/mod_tool/interface/file_system/file_system_context_actions.gd

Open the script editor automatically after creating a script extension. This deviates from the planned implementation discussed in #47, as it does not focus on the first selected script but simply opens them in order. This simplification was made to avoid unnecessary complexity. Since in most cases only one script at a time will be extended, the additional complexity is not worth it.
closes #47

feat: :sparkles: Open Script Editor after script extension creation

---

README.md
addons/mod_tool/plugin.cfg

- Changed the name to "Mod Loader Dev Tool" to make it visible when someone searches for "Mod Loader" on the Asset Library.
- Updated the readme with the current feature state.

chore: :memo: updated readme and plugin.cfg for v0.1.0

---

addons/mod_tool/interface/file_system/file_system_context_actions.gd
addons/mod_tool/interface/panel/tools_panel.gd

pass the `mod_tool_store` when initializing the `FileSystemContextActions`
closes #81

fix: :bug: fixed context actions not working

---

addons/mod_tool/interface/create_mod/create_mod.gd

The Select Button is getting reset to index 0, but the templates were added in alphabetical order to the options. Now the default templates are fixed in the first positions, starting with the default template.
closes #86

fix: :bug: fixed template select ui mismatch

---

addons/mod_tool/interface/manifest_editor/manifest_editor.gd
addons/mod_tool/interface/manifest_editor/manifest_editor.tscn

Fixed a bug where, after switching mods, the manifest editor would display fields from the previous mod if the current mod had no data for those inputs, resulting in the data from the previous mod being shown.
closes #89

fix: :bug: clear manifest inputs if no data present

---

addons/mod_tool/global/store.gd

After switching mods via "Connect existing Mod," the path `path_global_final_zip` was not updated, resulting in the wrong zip name on export.
closes #90

fix: :bug: fixed export zip name after mod switch

---

addons/mod_tool/interface/create_mod/create_mod.gd

Fixed template selection not showing anything if only default templates are present.
closes #99

fix: :bug: template selection with only default templates

---

.gitignore
addons/mod_tool/global/store.gd
addons/mod_tool/global/utils.gd
addons/mod_tool/interface/create_mod/create_mod.gd
addons/mod_tool/interface/file_system/file_system_context_actions.gd
addons/mod_tool/interface/hook_gen/hook_gen.gd
addons/mod_tool/interface/hook_gen/hook_gen.tscn
addons/mod_tool/interface/hook_restore/hook_restore.gd
addons/mod_tool/interface/hook_restore/hook_restore.tscn
addons/mod_tool/interface/panel/tools_panel.gd
addons/mod_tool/interface/panel/tools_panel.tscn
addons/mod_tool/scripts/hook_gen.gd

```text
res://addons/mod_loader/api/log.gd:396 - Invalid access to property or key 'ml_options' on a base object of type 'Node (mod_loader_store.gd)'.
res://addons/mod_loader/api/log.gd:416 - Invalid access to property or key 'logged_messages' on a base object of type 'Node (mod_loader_store.gd)'.
res://addons/mod_loader/api/log.gd:408 - Invalid access to property or key 'ml_options' on a base object of type 'Node (mod_loader_store.gd)'.
res://addons/mod_loader/api/log.gd:396 - Invalid access to property or key 'ml_options' on a base object of type 'Node (mod_loader_store.gd)'.
res://addons/mod_loader/api/log.gd:416 - Invalid access to property or key 'logged_messages' on a base object of type 'Node (mod_loader_store.gd)'.
res://addons/mod_loader/api/log.gd:408 - Invalid access to …
```

feat: :sparkles: mod hook gen

---

addons/mod_tool/global/store.gd

Missed some 7zip stuff in the Store
closes #122

refactor: :fire: remove 7zip check

---

addons/mod_tool/interface/create_mod/create_mod.gd
addons/mod_tool/interface/manifest_editor/manifest_editor.gd
addons/mod_tool/scripts/hook_gen.gd

We can use the manifest instance that we already have in the tool store.
Necessary because of 
- https://github.com/GodotModding/godot-mod-loader/pull/485

refactor: :recycle: non static `ModManifest`

---

addons/mod_tool/interface/panel/tools_panel.gd

If there is no manifest path stored, mod creation breaks because no Manifest instance is created. To fix this, the manifest of the template mod is now loaded.

fix: :bug: fall back to template manifest

---

addons/mod_tool/scripts/build_zip.gd

Alternatively, the -Update option can be passed to the PowerShell command on Windows.  
Adding an option to let the user decide whether the zip should be updated or deleted is probably the way to go.

refactor: :recycle: delete a previously exported mod zip
